### ISSUE TITLE
Analyze and clean up the remaining TODOs.

### ISSUE THREAD

**Issue by FabioMoreiraFM** [ramnasidharta/graphical-recipe#14]

**Comment by FabioMoreiraFM** [comment]
I'm doing the TODO of the graphicObject in the branch task2. I'm having trouble with rewrite code for every object.

**Comment by ramnaq** [comment]
Which problems are you facing?

**Comment by FabioMoreiraFM** [comment]
Declare a new method in GraphicObject, rewrite the same method for every class that inherits GraphicObject (When I could do once)
