### ISSUE TITLE
Add exception handlers to ListBox

### ISSUE THREAD

**Issue by FabioMoreiraFM** [ramnasidharta/graphical-recipe#15]
Object and Coordinate ListBox throw errors if no row is selected.

**Comment by FabioMoreiraFM** [comment]
After completing this issue, task 2 is finished.

**Comment by ramnaq** [comment]
Taking note:
* When clicking (-) button to delete an object from the ListBox, it prints out into the terminal a `Gtk-CRITICAL` error.
* About Coordinate LixtBox, when empty and clicking "Adicionar objeto", it crashes out the program. The same occurs for "Remover coordenanda" but only in the second click (weeird).

Gonna work on it later.

**Comment by ramnaq** [comment]
It looks done! See pull request #23.
