### ISSUE TITLE
Add polygon clipping functionality

### ISSUE THREAD

**Issue by FabioMoreiraFM** [ramnasidharta/graphical-recipe#28]

**Comment by ramnaq** [comment]
We can select the project in the right, label "Projects", to show the issues in the board, so we can move them to "in progress" -> "review" -> "done", etc.

**Comment by FabioMoreiraFM** [comment]
Ok, I just moved the issues I am working on right now.

**Comment by ramnaq** [comment]
Testing, I think a very specific bug occurred, but I couldn't reproduce it, so I'm not sure if it was a bug or I just missed something on the screen, because of rotating and zooming two polygons.
