### ISSUE TITLE
n+1 coordinates are needed to create a n-edge polygon

### ISSUE THREAD

**Issue by ramnaq** [ramnasidharta/graphical-recipe#8]
For example: creation of 5 coordinates are needed to create a square, where the last coordinate is the same as the first one.

This is a simple task: the method responsible for drawing a polygon with coordinates `coords` have to use `coords.front()` and `coords.back()` to draw the last edge, after the loop iteration over `coords`.

**Comment by FabioMoreiraFM** [comment]
Not implemented, but there is already a hidden check button in the interface to support this. If the user wants to fill the polygon, he selects this option and the software connect those points.

**Comment by ramnaq** [comment]
Don't you think it is okay let this being always true? That is, not having a check button, but simply when n-coordinates are inserted, a n-edge polygon is created. In my opinion, this is semantically correct (instead of having the possibility of not letting the check button marked, and being necessary n+1 coordinates to create a n-edge polygon).

Let me know your opinion. If you agree me, I already did it and I'm gonna merge. Otherwise, I can implement the check button functionality.

**Comment by FabioMoreiraFM** [comment]
I agree. I was thinking about let the user draw "not closed polygon", but this goes against the definition of a polygon.

**Comment by ramnaq** [comment]
Okay! Commited (in `small-fixes`) the change in `windows.glade` removing the `checkPoligonoPreenchido` `GtkCheckButton`; closing the issue.
